# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id_datatable', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('fecha', models.FloatField(blank=True, null=True)),
                ('actual', models.DateTimeField(blank=True, null=True)),
                ('metrica', models.IntegerField()),
                ('numsensor', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('repeat_after', models.IntegerField(default=0)),
                ('trigger', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='RaspTable',
            fields=[
                ('id_rasp', models.AutoField(primary_key=True, serialize=False)),
                ('numsensor', models.IntegerField(verbose_name='Numero sensores')),
                ('localaddress', models.CharField(max_length=15, verbose_name='LAN IP')),
                ('connectionhost', models.CharField(max_length=15, verbose_name='WAN IP')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorTable',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('msensor', models.CharField(max_length=8)),
                ('located', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('nserie', models.CharField(max_length=13)),
                ('nmodel', models.CharField(max_length=8)),
                ('nfirm', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_rasp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.RaspTable')),
            ],
        ),
        migrations.CreateModel(
            name='UsersRasp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rasp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.RaspTable')),
                ('id_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.UsersRasp'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.SensorTable'),
        ),
    ]
